// Daftar bahasa untuk pemilih bahasa (A-Z, lebih dari 100 bahasa)
// code: kode ISO yang dipakai sebagai key di i18n.js
// native: nama bahasa dalam bahasa itu sendiri
// en: nama bahasa dalam Bahasa Inggris (cadangan tampilan)
const LANGUAGES = [
  { code: "af", native: "Afrikaans", en: "Afrikaans" },
  { code: "sq", native: "Shqip", en: "Albanian" },
  { code: "am", native: "አማርኛ", en: "Amharic" },
  { code: "ar", native: "العربية", en: "Arabic" },
  { code: "hy", native: "Հայերեն", en: "Armenian" },
  { code: "az", native: "Azərbaycan", en: "Azerbaijani" },
  { code: "eu", native: "Euskara", en: "Basque" },
  { code: "be", native: "Беларуская", en: "Belarusian" },
  { code: "bn", native: "বাংলা", en: "Bengali" },
  { code: "bs", native: "Bosanski", en: "Bosnian" },
  { code: "bg", native: "Български", en: "Bulgarian" },
  { code: "my", native: "မြန်မာ", en: "Burmese" },
  { code: "ca", native: "Català", en: "Catalan" },
  { code: "ceb", native: "Cebuano", en: "Cebuano" },
  { code: "ny", native: "Chichewa", en: "Chichewa" },
  { code: "zh-CN", native: "简体中文", en: "Chinese (Simplified)" },
  { code: "zh-TW", native: "繁體中文", en: "Chinese (Traditional)" },
  { code: "co", native: "Corsu", en: "Corsican" },
  { code: "hr", native: "Hrvatski", en: "Croatian" },
  { code: "cs", native: "Čeština", en: "Czech" },
  { code: "da", native: "Dansk", en: "Danish" },
  { code: "nl", native: "Nederlands", en: "Dutch" },
  { code: "en", native: "English", en: "English" },
  { code: "eo", native: "Esperanto", en: "Esperanto" },
  { code: "et", native: "Eesti", en: "Estonian" },
  { code: "tl", native: "Filipino", en: "Filipino" },
  { code: "fi", native: "Suomi", en: "Finnish" },
  { code: "fr", native: "Français", en: "French" },
  { code: "fy", native: "Frysk", en: "Frisian" },
  { code: "gl", native: "Galego", en: "Galician" },
  { code: "ka", native: "ქართული", en: "Georgian" },
  { code: "de", native: "Deutsch", en: "German" },
  { code: "el", native: "Ελληνικά", en: "Greek" },
  { code: "gu", native: "ગુજરાતી", en: "Gujarati" },
  { code: "ht", native: "Kreyòl Ayisyen", en: "Haitian Creole" },
  { code: "ha", native: "Hausa", en: "Hausa" },
  { code: "haw", native: "ʻŌlelo Hawaiʻi", en: "Hawaiian" },
  { code: "he", native: "עברית", en: "Hebrew" },
  { code: "hi", native: "हिन्दी", en: "Hindi" },
  { code: "hmn", native: "Hmoob", en: "Hmong" },
  { code: "hu", native: "Magyar", en: "Hungarian" },
  { code: "is", native: "Íslenska", en: "Icelandic" },
  { code: "ig", native: "Igbo", en: "Igbo" },
  { code: "id", native: "Bahasa Indonesia", en: "Indonesian" },
  { code: "ga", native: "Gaeilge", en: "Irish" },
  { code: "it", native: "Italiano", en: "Italian" },
  { code: "ja", native: "日本語", en: "Japanese" },
  { code: "jv", native: "Basa Jawa", en: "Javanese" },
  { code: "kn", native: "ಕನ್ನಡ", en: "Kannada" },
  { code: "kk", native: "Қазақша", en: "Kazakh" },
  { code: "km", native: "ខ្មែរ", en: "Khmer" },
  { code: "rw", native: "Kinyarwanda", en: "Kinyarwanda" },
  { code: "ko", native: "한국어", en: "Korean" },
  { code: "ku", native: "Kurdî", en: "Kurdish" },
  { code: "ky", native: "Кыргызча", en: "Kyrgyz" },
  { code: "lo", native: "ລາວ", en: "Lao" },
  { code: "la", native: "Latina", en: "Latin" },
  { code: "lv", native: "Latviešu", en: "Latvian" },
  { code: "lt", native: "Lietuvių", en: "Lithuanian" },
  { code: "lb", native: "Lëtzebuergesch", en: "Luxembourgish" },
  { code: "mk", native: "Македонски", en: "Macedonian" },
  { code: "mg", native: "Malagasy", en: "Malagasy" },
  { code: "ms", native: "Bahasa Melayu", en: "Malay" },
  { code: "ml", native: "മലയാളം", en: "Malayalam" },
  { code: "mt", native: "Malti", en: "Maltese" },
  { code: "mi", native: "Māori", en: "Maori" },
  { code: "mr", native: "मराठी", en: "Marathi" },
  { code: "mn", native: "Монгол", en: "Mongolian" },
  { code: "ne", native: "नेपाली", en: "Nepali" },
  { code: "no", native: "Norsk", en: "Norwegian" },
  { code: "or", native: "ଓଡ଼ିଆ", en: "Odia" },
  { code: "ps", native: "پښتو", en: "Pashto" },
  { code: "fa", native: "فارسی", en: "Persian" },
  { code: "pl", native: "Polski", en: "Polish" },
  { code: "pt", native: "Português", en: "Portuguese" },
  { code: "pa", native: "ਪੰਜਾਬੀ", en: "Punjabi" },
  { code: "ro", native: "Română", en: "Romanian" },
  { code: "ru", native: "Русский", en: "Russian" },
  { code: "sm", native: "Gagana Sāmoa", en: "Samoan" },
  { code: "gd", native: "Gàidhlig", en: "Scots Gaelic" },
  { code: "sr", native: "Српски", en: "Serbian" },
  { code: "st", native: "Sesotho", en: "Sesotho" },
  { code: "sn", native: "Shona", en: "Shona" },
  { code: "sd", native: "سنڌي", en: "Sindhi" },
  { code: "si", native: "සිංහල", en: "Sinhala" },
  { code: "sk", native: "Slovenčina", en: "Slovak" },
  { code: "sl", native: "Slovenščina", en: "Slovenian" },
  { code: "so", native: "Soomaali", en: "Somali" },
  { code: "es", native: "Español", en: "Spanish" },
  { code: "su", native: "Basa Sunda", en: "Sundanese" },
  { code: "sw", native: "Kiswahili", en: "Swahili" },
  { code: "sv", native: "Svenska", en: "Swedish" },
  { code: "tg", native: "Тоҷикӣ", en: "Tajik" },
  { code: "ta", native: "தமிழ்", en: "Tamil" },
  { code: "tt", native: "Татарча", en: "Tatar" },
  { code: "te", native: "తెలుగు", en: "Telugu" },
  { code: "th", native: "ไทย", en: "Thai" },
  { code: "tr", native: "Türkçe", en: "Turkish" },
  { code: "tk", native: "Türkmençe", en: "Turkmen" },
  { code: "uk", native: "Українська", en: "Ukrainian" },
  { code: "ur", native: "اردو", en: "Urdu" },
  { code: "ug", native: "ئۇيغۇرچە", en: "Uyghur" },
  { code: "uz", native: "Oʻzbek", en: "Uzbek" },
  { code: "vi", native: "Tiếng Việt", en: "Vietnamese" },
  { code: "cy", native: "Cymraeg", en: "Welsh" },
  { code: "xh", native: "isiXhosa", en: "Xhosa" },
  { code: "yi", native: "ייִדיש", en: "Yiddish" },
  { code: "yo", native: "Yorùbá", en: "Yoruba" },
  { code: "zu", native: "isiZulu", en: "Zulu" },
];
